In [2]:
import pandas as pd

nhsn = pd.read_csv('nhsn_weekly_hospital_capacity_michigan_raw.csv')

nhsn.head()

,Week Ending Date,Geographic aggregation,Hospital Reporting Days,Percent Hospital Reporting Days,Number Hospitals Reporting Adult COVID-19 Admissions,Number Hospitals Reporting Pediatric COVID-19 Admissions,Number Hospitals Reporting Influenza Admissions,Number Hospitals Reporting Prevalent Influenza Hospitalizations,Number Hospitals Reporting Hospitalized Influenza ICU Patients,Number Hospitals Reporting Inpatient Beds,...,Absolute Change in the Percent Hospitals Reporting ICU Beds Occupied from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent Inpatient Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent ICU Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent Influenza Inpatient Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent COVID-19 ICU Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Percent Influenza ICU Bed Occupancy from Prior Week,Absolute Change in the Percent Hospitals Reporting Total COVID-19 Admissions from Prior Week,Absolute Change in the Percent Hospitals Reporting Prevalent COVID-19 Hospitalizations from Prior Week,Absolute Change in the Percent Hospitals Reporting Hospitalized COVID-19 ICU Patients from Prior Week
0,2023-01-07,MI,953,97.94%,138,138,138,138,138,138,...,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72
1,2023-01-14,MI,951,97.74%,137,137,137,137,137,137,...,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72
2,2023-01-21,MI,948,97.43%,136,136,136,136,136,136,...,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72,-0.72
3,2023-01-28,MI,943,96.92%,136,136,136,136,136,136,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2023-02-04,MI,948,97.43%,137,137,137,137,137,137,...,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72,0.72

In [3]:
nhsn.columns.tolist()

['Week Ending Date',
 'Geographic aggregation',
 'Hospital Reporting Days',
 'Percent Hospital Reporting Days',
 'Number Hospitals Reporting Adult COVID-19 Admissions',
 'Number Hospitals Reporting Pediatric COVID-19 Admissions',
 'Number Hospitals Reporting Influenza Admissions',
 'Number Hospitals Reporting Prevalent Influenza Hospitalizations',
 'Number Hospitals Reporting Hospitalized Influenza ICU Patients',
 'Number Hospitals Reporting Inpatient Beds',
 'Number Hospitals Reporting ICU Beds',
 'Number Hospitals Reporting Inpatient Beds Occupied',
 'Number Hospitals Reporting ICU Beds Occupied',
 'Number Hospitals Reporting Percent Inpatient Bed Occupancy',
 'Number Hospitals Reporting Percent ICU Bed Occupancy',
 'Number Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy',
 'Number Hospitals Reporting Percent Influenza Inpatient Bed Occupancy',
 'Number Hospitals Reporting Percent COVID-19 ICU Bed Occupancy',
 'Number Hospitals Reporting Percent Influenza ICU Bed Occupancy',
 'Number Hospitals Reporting Total COVID-19 Admissions',
 'Number Hospitals Reporting Prevalent COVID-19 Hospitalizations',
 'Number Hospitals Reporting Hospitalized COVID-19 ICU Patients',
 'Weekly Average Adult COVID-19 Admissions',
 'Weekly Total Adult COVID-19 Admissions',
 'Weekly Average Pediatric COVID-19 Admissions',
 'Weekly Total Pediatric COVID-19 Admissions',
 'Weekly Average COVID-19 Admissions',
 'Weekly Total COVID-19 Admissions',
 'Weekly Average Influenza Admissions',
 'Weekly Total Influenza Admissions',
 'Weekly Average Prevalent COVID-19 Hospitalizations',
 'Weekly Average Prevalent Influenza Hospitalizations',
 'Weekly Average Hospitalized COVID-19 ICU Patients',
 'Weekly Average Hospitalized Influenza ICU Patients',
 'Weekly Average Inpatient Beds',
 'Weekly Average ICU Beds',
 'Weekly Average Inpatient Beds Occupied',
 'Weekly Average ICU Beds Occupied',
 'Weekly Average Percent Inpatient Bed Occupancy',
 'Weekly Average Percent ICU Bed Occupancy',
 'Weekly Average Percent COVID-19 Inpatient Bed Occupancy',
 'Weekly Average Percent Influenza Inpatient Bed Occupancy',
 'Weekly Average Percent COVID-19 ICU Bed Occupancy',
 'Weekly Average Percent Influenza ICU Bed Occupancy',
 'Percent Adult COVID-19 Admissions',
 'Percent Pediatric COVID-19 Admissions',
 'Percent Hospitals Reporting Adult COVID-19 Admissions',
 'Percent Hospitals Reporting Pediatric COVID-19 Admissions',
 'Percent Hospitals Reporting Influenza Admissions',
 'Percent Hospitals Reporting Prevalent Influenza Hospitalizations',
 'Percent Hospitals Reporting Hospitalized Influenza ICU Patients',
 'Percent Hospitals Reporting Inpatient Beds',
 'Percent Hospitals Reporting ICU Beds',
 'Percent Hospitals Reporting Inpatient Beds Occupied',
 'Percent Hospitals Reporting ICU Beds Occupied',
 'Percent Hospitals Reporting Percent Inpatient Bed Occupancy',
 'Percent Hospitals Reporting Percent ICU Bed Occupancy',
 'Percent Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy',
 'Percent Hospitals Reporting Percent Influenza Inpatient Bed Occupancy',
 'Percent Hospitals Reporting Percent COVID-19 ICU Bed Occupancy',
 'Percent Hospitals Reporting Percent Influenza ICU Bed Occupancy',
 'Percent Hospitals Reporting Total COVID-19 Admissions',
 'Percent Hospitals Reporting Prevalent COVID-19 Hospitalizations',
 'Percent Hospitals Reporting Hospitalized COVID-19 ICU Patients',
 'Absolute Change in the Percent Hospitals Reporting Adult COVID-19 Admissions from Prior Week',
 'Absolute Change in the Percent Hospitals Reporting Pediatric COVID-19 Admissions from Prior Week',
 'Absolute Change in the Percent Hospitals Reporting Influenza Admissions from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Prevalent Influenza Hospitalizations from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Hospitalized Influenza ICU Patients from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Inpatient Beds from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting ICU Beds from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Inpatient Beds Occupied from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting ICU Beds Occupied from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent ICU Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent COVID-19 Inpatient Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent Influenza Inpatient Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent COVID-19 ICU Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Percent Influenza ICU Bed Occupancy from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Total COVID-19 Admissions from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Prevalent COVID-19 Hospitalizations from Prior Week ',
 'Absolute Change in the Percent Hospitals Reporting Hospitalized COVID-19 ICU Patients from Prior Week ']

In [4]:
nhsn_keep = [
    'Week Ending Date',
    'Geographic aggregation',
    'Percent Hospital Reporting Days',
    'Weekly Average Inpatient Beds',
    'Weekly Average ICU Beds',
    'Weekly Average Inpatient Beds Occupied',
    'Weekly Average ICU Beds Occupied',
    'Weekly Average Percent Inpatient Bed Occupancy',
    'Weekly Average Percent ICU Bed Occupancy',
    'Weekly Average Prevalent Influenza Hospitalizations',
    'Weekly Average Prevalent COVID-19 Hospitalizations',
    'Weekly Average Hospitalized COVID-19 ICU Patients'
]

nhsn_cur = nhsn[nhsn_keep].copy()
nhsn_cur.head()

,Week Ending Date,Geographic aggregation,Percent Hospital Reporting Days,Weekly Average Inpatient Beds,Weekly Average ICU Beds,Weekly Average Inpatient Beds Occupied,Weekly Average ICU Beds Occupied,Weekly Average Percent Inpatient Bed Occupancy,Weekly Average Percent ICU Bed Occupancy,Weekly Average Prevalent Influenza Hospitalizations,Weekly Average Prevalent COVID-19 Hospitalizations,Weekly Average Hospitalized COVID-19 ICU Patients
0,2023-01-07,MI,97.94%,"19,672.43","2,908.86","16,030.86","2,223.86",81.48%,76.44%,698.71,"1,208.86",149.71
1,2023-01-14,MI,97.74%,"19,439","2,886.43","15,941.14","2,181.86",81.97%,75.56%,402.57,"1,010.71",133.71
2,2023-01-21,MI,97.43%,"19,312.43","2,865.57","15,630.43","2,144",80.90%,74.76%,224.14,870.43,105.86
3,2023-01-28,MI,96.92%,"19,280.86","2,861.57","15,431.14","2,068.14",80.00%,72.24%,124.71,688,86.71
4,2023-02-04,MI,97.43%,"19,326.57","2,857.29","15,016.43","2,033.71",77.66%,71.13%,66.57,599.14,86.29

In [6]:
nhsn_cur.columns.tolist()

['Week Ending Date',
 'Geographic aggregation',
 'Percent Hospital Reporting Days',
 'Weekly Average Inpatient Beds',
 'Weekly Average ICU Beds',
 'Weekly Average Inpatient Beds Occupied',
 'Weekly Average ICU Beds Occupied',
 'Weekly Average Percent Inpatient Bed Occupancy',
 'Weekly Average Percent ICU Bed Occupancy',
 'Weekly Average Prevalent Influenza Hospitalizations',
 'Weekly Average Prevalent COVID-19 Hospitalizations',
 'Weekly Average Hospitalized COVID-19 ICU Patients']

In [7]:
nhsn_cur['Week Ending Date'] = pd.to_datetime(nhsn_cur['Week Ending Date'])
nhsn_cur['Percent Hospital Reporting Days'] = (
    nhsn_cur['Percent Hospital Reporting Days']
        .astype(str)
        .str.replace('%','')
        .astype(float)
)

In [8]:
nhsn_filt = nhsn_cur[
    (nhsn_cur['Geographic aggregation'] == 'MI') &
    (nhsn_cur['Percent Hospital Reporting Days'] >= 90) &
    (nhsn_cur['Week Ending Date'] >= '2023-01-01') &
    (nhsn_cur['Week Ending Date'] <= '2024-10-05')
].copy()

nhsn_filt.head()

,Week Ending Date,Geographic aggregation,Percent Hospital Reporting Days,Weekly Average Inpatient Beds,Weekly Average ICU Beds,Weekly Average Inpatient Beds Occupied,Weekly Average ICU Beds Occupied,Weekly Average Percent Inpatient Bed Occupancy,Weekly Average Percent ICU Bed Occupancy,Weekly Average Prevalent Influenza Hospitalizations,Weekly Average Prevalent COVID-19 Hospitalizations,Weekly Average Hospitalized COVID-19 ICU Patients
0,2023-01-07,MI,97.94,"19,672.43","2,908.86","16,030.86","2,223.86",81.48%,76.44%,698.71,"1,208.86",149.71
1,2023-01-14,MI,97.74,"19,439","2,886.43","15,941.14","2,181.86",81.97%,75.56%,402.57,"1,010.71",133.71
2,2023-01-21,MI,97.43,"19,312.43","2,865.57","15,630.43","2,144",80.90%,74.76%,224.14,870.43,105.86
3,2023-01-28,MI,96.92,"19,280.86","2,861.57","15,431.14","2,068.14",80.00%,72.24%,124.71,688,86.71
4,2023-02-04,MI,97.43,"19,326.57","2,857.29","15,016.43","2,033.71",77.66%,71.13%,66.57,599.14,86.29

In [9]:
nhsn_filt.shape
nhsn_filt['Week Ending Date'].min(), nhsn_filt['Week Ending Date'].max()
nhsn_filt.isna().sum()

Week Ending Date                                       0
Geographic aggregation                                 0
Percent Hospital Reporting Days                        0
Weekly Average Inpatient Beds                          0
Weekly Average ICU Beds                                0
Weekly Average Inpatient Beds Occupied                 0
Weekly Average ICU Beds Occupied                       0
Weekly Average Percent Inpatient Bed Occupancy         0
Weekly Average Percent ICU Bed Occupancy               0
Weekly Average Prevalent Influenza Hospitalizations    0
Weekly Average Prevalent COVID-19 Hospitalizations     0
Weekly Average Hospitalized COVID-19 ICU Patients      0
dtype: int64

In [10]:
nhsn_final = nhsn_filt.rename(columns={
    'Week Ending Date': 'week_end',
    'Geographic aggregation': 'geo',
    'Percent Hospital Reporting Days': 'pct_reporting_days',

    'Weekly Average Inpatient Beds': 'avg_inpatient_beds',
    'Weekly Average ICU Beds': 'avg_icu_beds',
    'Weekly Average Inpatient Beds Occupied': 'avg_inpatient_beds_used',
    'Weekly Average ICU Beds Occupied': 'avg_icu_beds_used',

    'Weekly Average Percent Inpatient Bed Occupancy': 'pct_inpatient_beds_occupied',
    'Weekly Average Percent ICU Bed Occupancy': 'pct_icu_beds_occupied',

    'Weekly Average Prevalent Influenza Hospitalizations': 'avg_flu_hospitalizations',
    'Weekly Average Prevalent COVID-19 Hospitalizations': 'avg_covid_hospitalizations',
    'Weekly Average Hospitalized COVID-19 ICU Patients': 'avg_covid_icu_patients'
}).copy()

In [11]:
for c in ['pct_inpatient_beds_occupied', 'pct_icu_beds_occupied']:
    nhsn_final[c] = nhsn_final[c].astype(str).str.replace('%','').astype(float)

nhsn_final.head()

,week_end,geo,pct_reporting_days,avg_inpatient_beds,avg_icu_beds,avg_inpatient_beds_used,avg_icu_beds_used,pct_inpatient_beds_occupied,pct_icu_beds_occupied,avg_flu_hospitalizations,avg_covid_hospitalizations,avg_covid_icu_patients
0,2023-01-07,MI,97.94,"19,672.43","2,908.86","16,030.86","2,223.86",81.48,76.44,698.71,"1,208.86",149.71
1,2023-01-14,MI,97.74,"19,439","2,886.43","15,941.14","2,181.86",81.97,75.56,402.57,"1,010.71",133.71
2,2023-01-21,MI,97.43,"19,312.43","2,865.57","15,630.43","2,144",80.90,74.76,224.14,870.43,105.86
3,2023-01-28,MI,96.92,"19,280.86","2,861.57","15,431.14","2,068.14",80.00,72.24,124.71,688,86.71
4,2023-02-04,MI,97.43,"19,326.57","2,857.29","15,016.43","2,033.71",77.66,71.13,66.57,599.14,86.29

In [12]:
nhsn_final.to_csv(
    'data_curated/nhsn_capacity_weekly_mi_curated.csv',
    index=False
)

In [13]:
nhsn_final.shape
nhsn_final['week_end'].min(), nhsn_final['week_end'].max()

(Timestamp('2023-01-07 00:00:00'), Timestamp('2024-04-27 00:00:00'))

NameError: name 'mi_state_2023' is not defined